#!/bin/bash
#
#https://wiki.ubuntu.com/Django
#http://docs.djangoproject.com/en/dev/howto/deployment/modpython/?from=olddocs
#
apt-get install pure-ftpd-mysql
cp /var/lib/vz/private/105/etc/pure-ftpd/db/mysql.conf /var/lib/vz/private/102/etc/pure-ftpd/db/mysql.conf



groupadd playground
useradd -s /bin/false -d /bin/null -c "wcf1 groupid 18" -g playground playground

django-admin startproject playground
chown -R playground.playground /home/playground 

vim /root/sites/django-playground.conf
<Location "/playground/">
    SetEnv DJANGO_SETTINGS_MODULE playground.settings
    PythonInterpreter playground
</Location>

/etc/init.d/apache2 force-reload
