#!/bin/bash
basedir=`dirname "$0"`

# exit on error
set -e

AS_HOST=localhost
AS_ADMINUSER=admin
AS_ADMINPASSWORD=adminadmin
AS_ADMINPORT=4848

dirs=`find /home -mindepth 1 -maxdepth 1`

for dir in $dirs
do
	cd $dir
	
	if [ -d ".svn" ]; then
		shortname=`basename "$dir"`

		oldrev=$(svn info |grep '^Revision: '|sed 's/Revision: //g')
		svn update
		newrev=$(svn info |grep '^Revision: '|sed 's/Revision: //g')

		# force redeploy
		if [ "$oldrev" != "$newrev" ]; then
			# replace <display-name> in web.xml
			sed "s/<display-name>[^<]*<\/display-name>/<display-name>${shortname}<\/display-name>/g" WEB-INF/web.xml > WEB-INF/web.xml2
			mv WEB-INF/web.xml2 WEB-INF/web.xml
	
			# replace <context-root> in sun-web.xml
			sed "s/<context-root>[^<]*<\/context-root>/<context-root>\/${shortname}<\/context-root>/g" WEB-INF/sun-web.xml > WEB-INF/sun-web.xml2
			mv WEB-INF/sun-web.xml2 WEB-INF/sun-web.xml
			
			# did any changes occur to these files, revert them!
			svn commit WEB-INF/web.xml WEB-INF/sun-web.xml -m "glassfish robot"
			
			# autodeploy as war
			# zip -r /tmp/$shortname.zip * -x *\.svn*
			# mv /tmp/$shortname.zip /var/lib/glassfishv2/domains/domain1/autodeploy/$shortname.war
		fi
	fi
done
