#!/bin/bash
#
# parameters
#	$1 = project shortname
#	$2 = boolean create skeleton
basedir=`dirname "$0"`

# exit on error
set -e

# add user and group
groupadd $1
useradd -s /bin/false -d /bin/null -c "wcf1 {$1}" -g $1 $1

# check out from svn
cd /home
svn checkout https://svn.easy-coding.de/$1/trunk $1

# check in skeleton
if [ $2 ]; then
	cd /tmp
	rails /tmp/$1
	
	# place workaround
	sed -e '$d' /home/$1/config/environment.rb > /home/$1/config/environment.rb2
	echo -e "  # from gems 2.2 you need this workaround\n  # http://groups.google.com/group/phusion-passenger/browse_thread/thread/d3e7b1f524f5ab62?pli=1\n  config.action_controller.relative_url_root = \"/${1}\"" >> /home/$1/config/environment.rb2
	mv /home/$1/config/environment.rb2 /home/$1/config/environment.rb
	
	mv /tmp/$1/* /home/$1
	svn add /home/$1/*
	svn commit /home/$1 -m "rails skeleton"
fi

# change ownership
chown -R $1.$1 /home/$1 
ln -s /home/$1/public/ /var/www/$1

# configure webserver
echo -e "RailsBaseURI /${1}" > /root/sites/rails-$1.conf

# reload webserver config
/etc/init.d/apache2 force-reload
