#!/bin/bash
basedir=`dirname "$0"`

# exit on error
set -e

dirs=`find /home -mindepth 1 -maxdepth 1`

for dir in $dirs
do
	cd $dir
	
	if [ -d ".svn" ]; then
		oldrev=$(svn info |grep '^Revision: '|sed 's/Revision: //g')
		svn update
		newrev=$(svn info |grep '^Revision: '|sed 's/Revision: //g')

		# force redeploy
		#if [ "$oldrev" != "$newrev" ]; then
		#	touch tmp/restart.txt
		#fi
	fi
done
