#!/bin/bash
#
# parameters
#	$1 = project shortname
#	$2 = longname
basedir=`dirname "$0"`

# exit on error
set -e

# create trac system
trac-admin /var/www/trac.easy-coding.de/web/trac/$1 initenv $2 sqlite:db/trac.db /var/www/svn.easy-coding.de/web/svn/$1 /usr/share/trac/templates

# change privileges of guests
trac-admin /var/www/trac.easy-coding.de/web/trac/$1 permission remove anonymous WIKI_CREATE WIKI_MODIFY

# change ownership
chown -R www-data.www-data /var/www/trac.easy-coding.de/web/trac/$1

# configure webserver
echo -e "<Location /trac/${1}/login>\n require group ${1}\n</Location>" > /root/sites/trac-${1}.conf

# reload webserver config
/etc/init.d/apache2 force-reload
